name: BaseDataModule
params:
  preprocessing: # applied to all datasets
    apply: True
    name: VocPreprocessing
  augmentation: # applied to all datasets
    apply: True
    augmentations:
      - name: VocTransFlipud
      - name: VocTransFliplr
      - name: VocTransRot270
      - name: VocTransRot180
  extra:
    data_ignore_index: &data_ignore_index 255
    number_of_classes: 21

  datasets:
    - name : SplitDataset
      params:
        reference_names: ["train","valid"]
        split_ratios: [0.8, 0.2]
        parent_dataset:
          name: VocDataset
          params:
            root_dir: E:/Documents/DATA/VOC2012_train_val/

  common_dataloader_params:
    num_workers: 6
    batch_size: 6
    shuffle: False
    drop_last: False
    collate_fn: null

  dataloaders:
    train:
      name: DataLoader
      params:
        dataset_reference_name: train
        shuffle: True
        drop_last: True
    valid:
      name: DataLoader
      params:
        dataset_reference_name: valid
        shuffle: False
        drop_last: True
