# Define the root keys with their types
experiment_name: str()
experiment_checkpoint_directory: str()
experiment_logging_directory: str()

datamodule:
  name: registered_datamodule()
  params:
    preprocessing:
      apply: bool(required=False)
      name: registered_preprocessing(required=False)
      params: include('params')
    augmentation:
      apply: bool(required=False)
      augmentations: list(include('named_entity'))
    datasets: list(include('dataset'))
    common_loaders_params: map(key=str(), required=False)
    dataloaders: map(include('dataloader'), key=enum("train", "valid", "test", "predict"))

trainer:
  name: registered_trainer()
  params: include('params')
  callbacks: list(include('callback'))
  loggers: list(include('logger'))

task:
  name: registered_task()
  learner: include('learner')

# Define reusable components
---
dataset:
  name: registered_dataset()
  reference_name: str(required=False)
  params: include('params')

dataloader:
  name: str()
  respective_dataset_name: str()
  params: include('params')

callback:
  name: registered_callback()
  params: include('params')

logger:
  name: registered_logger()
  params: include('params')

learner:
  name: registered_learner()
  params: include('params')
  model: include('model')
  optimizer:
    name: registered_optimizer()
    params: include('params')
  lr_scheduler:
    name: registered_scheduler()
    params: include('params')
  critireon:
    name: registered_critireon()
    params: include('params')

model:
  name: registered_model()
  params: include('params')

params:  # Reusable component for params
  map(any(), required=False)

named_entity:
  name: str()
  params: include('params')
